// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.3
// source: proto/bread.proto

package bread

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{0}
}

type BreadQueueSize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quantity int64 `protobuf:"varint,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *BreadQueueSize) Reset() {
	*x = BreadQueueSize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BreadQueueSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreadQueueSize) ProtoMessage() {}

func (x *BreadQueueSize) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreadQueueSize.ProtoReflect.Descriptor instead.
func (*BreadQueueSize) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{1}
}

func (x *BreadQueueSize) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Client struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type   string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Active bool   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Admin  bool   `protobuf:"varint,5,opt,name=admin,proto3" json:"admin,omitempty"`
}

func (x *Client) Reset() {
	*x = Client{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{2}
}

func (x *Client) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Client) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Client) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Client) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Client) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

type ClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client *Client `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{3}
}

func (x *ClientRequest) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

type ClientResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client *Client `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
}

func (x *ClientResponse) Reset() {
	*x = ClientResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResponse) ProtoMessage() {}

func (x *ClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResponse.ProtoReflect.Descriptor instead.
func (*ClientResponse) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{4}
}

func (x *ClientResponse) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

type ClientsInQueue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clients []*Client `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	Message string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error   string    `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ClientsInQueue) Reset() {
	*x = ClientsInQueue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientsInQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientsInQueue) ProtoMessage() {}

func (x *ClientsInQueue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientsInQueue.ProtoReflect.Descriptor instead.
func (*ClientsInQueue) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{5}
}

func (x *ClientsInQueue) GetClients() []*Client {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *ClientsInQueue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ClientsInQueue) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Bread struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type     string  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Quantity int64   `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price    float32 `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Message  string  `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Error    string  `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Bread) Reset() {
	*x = Bread{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bread) ProtoMessage() {}

func (x *Bread) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bread.ProtoReflect.Descriptor instead.
func (*Bread) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{6}
}

func (x *Bread) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bread) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bread) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Bread) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Bread) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Bread) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Bread) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BreadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bread *Bread `protobuf:"bytes,1,opt,name=bread,proto3" json:"bread,omitempty"`
}

func (x *BreadRequest) Reset() {
	*x = BreadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreadRequest) ProtoMessage() {}

func (x *BreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreadRequest.ProtoReflect.Descriptor instead.
func (*BreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{7}
}

func (x *BreadRequest) GetBread() *Bread {
	if x != nil {
		return x.Bread
	}
	return nil
}

type BreadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bread   *Bread `protobuf:"bytes,1,opt,name=bread,proto3" json:"bread,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *BreadResponse) Reset() {
	*x = BreadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreadResponse) ProtoMessage() {}

func (x *BreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreadResponse.ProtoReflect.Descriptor instead.
func (*BreadResponse) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{8}
}

func (x *BreadResponse) GetBread() *Bread {
	if x != nil {
		return x.Bread
	}
	return nil
}

func (x *BreadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BreadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BakeryRequestList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Breads []*BreadRequest `protobuf:"bytes,1,rep,name=breads,proto3" json:"breads,omitempty"`
}

func (x *BakeryRequestList) Reset() {
	*x = BakeryRequestList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BakeryRequestList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BakeryRequestList) ProtoMessage() {}

func (x *BakeryRequestList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BakeryRequestList.ProtoReflect.Descriptor instead.
func (*BakeryRequestList) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{9}
}

func (x *BakeryRequestList) GetBreads() []*BreadRequest {
	if x != nil {
		return x.Breads
	}
	return nil
}

type BakeryResponseList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Breads []*BreadResponse `protobuf:"bytes,1,rep,name=breads,proto3" json:"breads,omitempty"`
}

func (x *BakeryResponseList) Reset() {
	*x = BakeryResponseList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BakeryResponseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BakeryResponseList) ProtoMessage() {}

func (x *BakeryResponseList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BakeryResponseList.ProtoReflect.Descriptor instead.
func (*BakeryResponseList) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{10}
}

func (x *BakeryResponseList) GetBreads() []*BreadResponse {
	if x != nil {
		return x.Breads
	}
	return nil
}

type BuyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type     string  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Quantity int64   `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price    float32 `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Message  string  `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Error    string  `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *BuyRequest) Reset() {
	*x = BuyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyRequest) ProtoMessage() {}

func (x *BuyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyRequest.ProtoReflect.Descriptor instead.
func (*BuyRequest) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{11}
}

func (x *BuyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BuyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BuyRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BuyRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BuyRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BuyRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BuyRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BuyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type     string  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Quantity int64   `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price    float32 `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Message  string  `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Error    string  `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *BuyResponse) Reset() {
	*x = BuyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyResponse) ProtoMessage() {}

func (x *BuyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyResponse.ProtoReflect.Descriptor instead.
func (*BuyResponse) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{12}
}

func (x *BuyResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BuyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BuyResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BuyResponse) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BuyResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BuyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BuyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_bread_proto protoreflect.FileDescriptor

var file_proto_bread_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x62, 0x72, 0x65, 0x61, 0x64, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x2c, 0x0a, 0x0e, 0x42, 0x72, 0x65, 0x61, 0x64, 0x51, 0x75, 0x65, 0x75,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x22, 0x6e, 0x0a, 0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x22, 0x36, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x25, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x37, 0x0a, 0x0e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x72,
	0x65, 0x61, 0x64, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x22, 0x69, 0x0a, 0x0e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x49, 0x6e, 0x51,
	0x75, 0x65, 0x75, 0x65, 0x12, 0x27, 0x0a, 0x07, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xa1, 0x01,
	0x0a, 0x05, 0x42, 0x72, 0x65, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x32, 0x0a, 0x0c, 0x42, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x22, 0x0a, 0x05, 0x62, 0x72, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x42, 0x72, 0x65, 0x61, 0x64, 0x52, 0x05,
	0x62, 0x72, 0x65, 0x61, 0x64, 0x22, 0x63, 0x0a, 0x0d, 0x42, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x62, 0x72, 0x65, 0x61, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x42, 0x72,
	0x65, 0x61, 0x64, 0x52, 0x05, 0x62, 0x72, 0x65, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x40, 0x0a, 0x11, 0x42, 0x61,
	0x6b, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x2b, 0x0a, 0x06, 0x62, 0x72, 0x65, 0x61, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x42, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x06, 0x62, 0x72, 0x65, 0x61, 0x64, 0x73, 0x22, 0x42, 0x0a, 0x12,
	0x42, 0x61, 0x6b, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x2c, 0x0a, 0x06, 0x62, 0x72, 0x65, 0x61, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x42, 0x72, 0x65, 0x61, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x62, 0x72, 0x65, 0x61, 0x64, 0x73,
	0x22, 0xa6, 0x01, 0x0a, 0x0a, 0x42, 0x75, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xa7, 0x01, 0x0a, 0x0b, 0x42, 0x75,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x32, 0xdf, 0x01, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x75, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x54, 0x6f, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x15, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64,
	0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x49, 0x6e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x1a,
	0x15, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x49,
	0x6e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x10, 0x53, 0x68, 0x6f, 0x77,
	0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x15, 0x2e, 0x62,
	0x72, 0x65, 0x61, 0x64, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x49, 0x6e, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x1a, 0x15, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x73, 0x49, 0x6e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x15,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x46, 0x72, 0x6f, 0x6d,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x15, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x73, 0x49, 0x6e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x1a, 0x15, 0x2e, 0x62,
	0x72, 0x65, 0x61, 0x64, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x49, 0x6e, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x22, 0x00, 0x32, 0x85, 0x01, 0x0a, 0x09, 0x4d, 0x61, 0x6b, 0x65, 0x42, 0x72,
	0x65, 0x61, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x4d, 0x61, 0x6b, 0x65, 0x42, 0x72, 0x65, 0x61, 0x64,
	0x12, 0x13, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x42, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x42, 0x72,
	0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a,
	0x0f, 0x41, 0x64, 0x64, 0x42, 0x72, 0x65, 0x61, 0x64, 0x54, 0x6f, 0x51, 0x75, 0x65, 0x75, 0x65,
	0x12, 0x13, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x42, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x42, 0x72,
	0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x4d, 0x0a,
	0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x3d, 0x0a,
	0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x2e,
	0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0xd9, 0x01, 0x0a,
	0x12, 0x42, 0x61, 0x6b, 0x65, 0x72, 0x79, 0x42, 0x72, 0x65, 0x61, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x42, 0x72, 0x65, 0x61, 0x64, 0x73, 0x12, 0x18, 0x2e, 0x62, 0x72, 0x65, 0x61,
	0x64, 0x2e, 0x42, 0x61, 0x6b, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x42, 0x61, 0x6b, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00,
	0x12, 0x38, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x72, 0x65, 0x61, 0x64, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x12, 0x0c, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x15, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x42, 0x72, 0x65, 0x61, 0x64, 0x51,
	0x75, 0x65, 0x75, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x11, 0x42, 0x75,
	0x79, 0x42, 0x72, 0x65, 0x61, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12,
	0x11, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x42, 0x75, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x42, 0x75, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x61, 0x6c, 0x76, 0x61, 0x72, 0x61, 0x64, 0x6f,
	0x32, 0x30, 0x30, 0x34, 0x2f, 0x62, 0x61, 0x6b, 0x65, 0x72, 0x79, 0x2d, 0x67, 0x6f, 0x2f, 0x62,
	0x72, 0x65, 0x61, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_bread_proto_rawDescOnce sync.Once
	file_proto_bread_proto_rawDescData = file_proto_bread_proto_rawDesc
)

func file_proto_bread_proto_rawDescGZIP() []byte {
	file_proto_bread_proto_rawDescOnce.Do(func() {
		file_proto_bread_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_bread_proto_rawDescData)
	})
	return file_proto_bread_proto_rawDescData
}

var file_proto_bread_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_bread_proto_goTypes = []interface{}{
	(*Empty)(nil),              // 0: bread.Empty
	(*BreadQueueSize)(nil),     // 1: bread.BreadQueueSize
	(*Client)(nil),             // 2: bread.Client
	(*ClientRequest)(nil),      // 3: bread.ClientRequest
	(*ClientResponse)(nil),     // 4: bread.ClientResponse
	(*ClientsInQueue)(nil),     // 5: bread.ClientsInQueue
	(*Bread)(nil),              // 6: bread.Bread
	(*BreadRequest)(nil),       // 7: bread.BreadRequest
	(*BreadResponse)(nil),      // 8: bread.BreadResponse
	(*BakeryRequestList)(nil),  // 9: bread.BakeryRequestList
	(*BakeryResponseList)(nil), // 10: bread.BakeryResponseList
	(*BuyRequest)(nil),         // 11: bread.BuyRequest
	(*BuyResponse)(nil),        // 12: bread.BuyResponse
}
var file_proto_bread_proto_depIdxs = []int32{
	2,  // 0: bread.ClientRequest.client:type_name -> bread.Client
	2,  // 1: bread.ClientResponse.client:type_name -> bread.Client
	2,  // 2: bread.ClientsInQueue.clients:type_name -> bread.Client
	6,  // 3: bread.BreadRequest.bread:type_name -> bread.Bread
	6,  // 4: bread.BreadResponse.bread:type_name -> bread.Bread
	7,  // 5: bread.BakeryRequestList.breads:type_name -> bread.BreadRequest
	8,  // 6: bread.BakeryResponseList.breads:type_name -> bread.BreadResponse
	5,  // 7: bread.QueueService.AddClientToQueue:input_type -> bread.ClientsInQueue
	5,  // 8: bread.QueueService.ShowWaitingQueue:input_type -> bread.ClientsInQueue
	5,  // 9: bread.QueueService.DeleteClientFromQueue:input_type -> bread.ClientsInQueue
	7,  // 10: bread.MakeBread.MakeBread:input_type -> bread.BreadRequest
	7,  // 11: bread.MakeBread.AddBreadToQueue:input_type -> bread.BreadRequest
	3,  // 12: bread.CreateClient.CreateClient:input_type -> bread.ClientRequest
	9,  // 13: bread.BakeryBreadService.GetAvailableBreads:input_type -> bread.BakeryRequestList
	0,  // 14: bread.BakeryBreadService.CheckBreadQueue:input_type -> bread.Empty
	11, // 15: bread.BakeryBreadService.BuyBreadFromQueue:input_type -> bread.BuyRequest
	5,  // 16: bread.QueueService.AddClientToQueue:output_type -> bread.ClientsInQueue
	5,  // 17: bread.QueueService.ShowWaitingQueue:output_type -> bread.ClientsInQueue
	5,  // 18: bread.QueueService.DeleteClientFromQueue:output_type -> bread.ClientsInQueue
	8,  // 19: bread.MakeBread.MakeBread:output_type -> bread.BreadResponse
	8,  // 20: bread.MakeBread.AddBreadToQueue:output_type -> bread.BreadResponse
	4,  // 21: bread.CreateClient.CreateClient:output_type -> bread.ClientResponse
	10, // 22: bread.BakeryBreadService.GetAvailableBreads:output_type -> bread.BakeryResponseList
	1,  // 23: bread.BakeryBreadService.CheckBreadQueue:output_type -> bread.BreadQueueSize
	12, // 24: bread.BakeryBreadService.BuyBreadFromQueue:output_type -> bread.BuyResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_bread_proto_init() }
func file_proto_bread_proto_init() {
	if File_proto_bread_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_bread_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BreadQueueSize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Client); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientsInQueue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bread); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BreadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BreadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BakeryRequestList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BakeryResponseList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_bread_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_bread_proto_goTypes,
		DependencyIndexes: file_proto_bread_proto_depIdxs,
		MessageInfos:      file_proto_bread_proto_msgTypes,
	}.Build()
	File_proto_bread_proto = out.File
	file_proto_bread_proto_rawDesc = nil
	file_proto_bread_proto_goTypes = nil
	file_proto_bread_proto_depIdxs = nil
}
