// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/bread.proto

package bread

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BreadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Quantity int64  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Message  string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BreadRequest) Reset() {
	*x = BreadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreadRequest) ProtoMessage() {}

func (x *BreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreadRequest.ProtoReflect.Descriptor instead.
func (*BreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{0}
}

func (x *BreadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BreadRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BreadRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BreadRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BreadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Quantity int64  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price    int64  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Message  string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Error    string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *BreadResponse) Reset() {
	*x = BreadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreadResponse) ProtoMessage() {}

func (x *BreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreadResponse.ProtoReflect.Descriptor instead.
func (*BreadResponse) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{1}
}

func (x *BreadResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BreadResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BreadResponse) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BreadResponse) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BreadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BreadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CakesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Quantity int64  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Message  string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CakesRequest) Reset() {
	*x = CakesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CakesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CakesRequest) ProtoMessage() {}

func (x *CakesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CakesRequest.ProtoReflect.Descriptor instead.
func (*CakesRequest) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{2}
}

func (x *CakesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CakesRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CakesRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CakesRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CakesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Quantity int64  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price    int64  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Message  string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Error    string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CakesResponse) Reset() {
	*x = CakesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CakesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CakesResponse) ProtoMessage() {}

func (x *CakesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CakesResponse.ProtoReflect.Descriptor instead.
func (*CakesResponse) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{3}
}

func (x *CakesResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CakesResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CakesResponse) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CakesResponse) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CakesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CakesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CookiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Quantity int64  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Message  string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CookiesRequest) Reset() {
	*x = CookiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CookiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CookiesRequest) ProtoMessage() {}

func (x *CookiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CookiesRequest.ProtoReflect.Descriptor instead.
func (*CookiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{4}
}

func (x *CookiesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CookiesRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CookiesRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CookiesRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CookiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Quantity int64  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price    int64  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Message  string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Error    string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CookiesResponse) Reset() {
	*x = CookiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CookiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CookiesResponse) ProtoMessage() {}

func (x *CookiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CookiesResponse.ProtoReflect.Descriptor instead.
func (*CookiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{5}
}

func (x *CookiesResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CookiesResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CookiesResponse) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CookiesResponse) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CookiesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CookiesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ClientsInQueue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clients int64 `protobuf:"varint,1,opt,name=clients,proto3" json:"clients,omitempty"`
}

func (x *ClientsInQueue) Reset() {
	*x = ClientsInQueue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientsInQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientsInQueue) ProtoMessage() {}

func (x *ClientsInQueue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientsInQueue.ProtoReflect.Descriptor instead.
func (*ClientsInQueue) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{6}
}

func (x *ClientsInQueue) GetClients() int64 {
	if x != nil {
		return x.Clients
	}
	return 0
}

type Bread struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Quantity int64  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price    int64  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Message  string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Error    string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Bread) Reset() {
	*x = Bread{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bread) ProtoMessage() {}

func (x *Bread) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bread.ProtoReflect.Descriptor instead.
func (*Bread) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{7}
}

func (x *Bread) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bread) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Bread) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Bread) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Bread) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Bread) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Cakes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Quantity int64  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price    int64  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Message  string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Error    string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Cakes) Reset() {
	*x = Cakes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cakes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cakes) ProtoMessage() {}

func (x *Cakes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cakes.ProtoReflect.Descriptor instead.
func (*Cakes) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{8}
}

func (x *Cakes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cakes) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Cakes) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Cakes) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Cakes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Cakes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Cookies struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Quantity int64  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price    int64  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Message  string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Error    string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Cookies) Reset() {
	*x = Cookies{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cookies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cookies) ProtoMessage() {}

func (x *Cookies) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cookies.ProtoReflect.Descriptor instead.
func (*Cookies) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{9}
}

func (x *Cookies) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cookies) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Cookies) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Cookies) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Cookies) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Cookies) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BreadList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Breads  []*Bread   `protobuf:"bytes,1,rep,name=breads,proto3" json:"breads,omitempty"`
	Cakes   []*Cakes   `protobuf:"bytes,2,rep,name=cakes,proto3" json:"cakes,omitempty"`
	Cookies []*Cookies `protobuf:"bytes,3,rep,name=cookies,proto3" json:"cookies,omitempty"`
}

func (x *BreadList) Reset() {
	*x = BreadList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BreadList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreadList) ProtoMessage() {}

func (x *BreadList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreadList.ProtoReflect.Descriptor instead.
func (*BreadList) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{10}
}

func (x *BreadList) GetBreads() []*Bread {
	if x != nil {
		return x.Breads
	}
	return nil
}

func (x *BreadList) GetCakes() []*Cakes {
	if x != nil {
		return x.Cakes
	}
	return nil
}

func (x *BreadList) GetCookies() []*Cookies {
	if x != nil {
		return x.Cookies
	}
	return nil
}

type BakeryRequestList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Breads []*BreadRequest `protobuf:"bytes,1,rep,name=breads,proto3" json:"breads,omitempty"`
}

func (x *BakeryRequestList) Reset() {
	*x = BakeryRequestList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BakeryRequestList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BakeryRequestList) ProtoMessage() {}

func (x *BakeryRequestList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BakeryRequestList.ProtoReflect.Descriptor instead.
func (*BakeryRequestList) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{11}
}

func (x *BakeryRequestList) GetBreads() []*BreadRequest {
	if x != nil {
		return x.Breads
	}
	return nil
}

type BakeryResponseList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Breads []*BreadResponse `protobuf:"bytes,1,rep,name=breads,proto3" json:"breads,omitempty"`
}

func (x *BakeryResponseList) Reset() {
	*x = BakeryResponseList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BakeryResponseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BakeryResponseList) ProtoMessage() {}

func (x *BakeryResponseList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BakeryResponseList.ProtoReflect.Descriptor instead.
func (*BakeryResponseList) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{12}
}

func (x *BakeryResponseList) GetBreads() []*BreadResponse {
	if x != nil {
		return x.Breads
	}
	return nil
}

type CakesRequestList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cakes []*CakesRequest `protobuf:"bytes,1,rep,name=cakes,proto3" json:"cakes,omitempty"`
}

func (x *CakesRequestList) Reset() {
	*x = CakesRequestList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CakesRequestList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CakesRequestList) ProtoMessage() {}

func (x *CakesRequestList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CakesRequestList.ProtoReflect.Descriptor instead.
func (*CakesRequestList) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{13}
}

func (x *CakesRequestList) GetCakes() []*CakesRequest {
	if x != nil {
		return x.Cakes
	}
	return nil
}

type CakesResponseList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cakes []*CakesResponse `protobuf:"bytes,1,rep,name=cakes,proto3" json:"cakes,omitempty"`
}

func (x *CakesResponseList) Reset() {
	*x = CakesResponseList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CakesResponseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CakesResponseList) ProtoMessage() {}

func (x *CakesResponseList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CakesResponseList.ProtoReflect.Descriptor instead.
func (*CakesResponseList) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{14}
}

func (x *CakesResponseList) GetCakes() []*CakesResponse {
	if x != nil {
		return x.Cakes
	}
	return nil
}

type CookiesRequestList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cookies []*CookiesRequest `protobuf:"bytes,1,rep,name=cookies,proto3" json:"cookies,omitempty"`
}

func (x *CookiesRequestList) Reset() {
	*x = CookiesRequestList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CookiesRequestList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CookiesRequestList) ProtoMessage() {}

func (x *CookiesRequestList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CookiesRequestList.ProtoReflect.Descriptor instead.
func (*CookiesRequestList) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{15}
}

func (x *CookiesRequestList) GetCookies() []*CookiesRequest {
	if x != nil {
		return x.Cookies
	}
	return nil
}

type CookiesResponseList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cookies []*CookiesResponse `protobuf:"bytes,1,rep,name=cookies,proto3" json:"cookies,omitempty"`
}

func (x *CookiesResponseList) Reset() {
	*x = CookiesResponseList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bread_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CookiesResponseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CookiesResponseList) ProtoMessage() {}

func (x *CookiesResponseList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CookiesResponseList.ProtoReflect.Descriptor instead.
func (*CookiesResponseList) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{16}
}

func (x *CookiesResponseList) GetCookies() []*CookiesResponse {
	if x != nil {
		return x.Cookies
	}
	return nil
}

var File_proto_bread_proto protoreflect.FileDescriptor

var file_proto_bread_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x62, 0x72, 0x65, 0x61, 0x64, 0x22, 0x6c, 0x0a, 0x0c, 0x42, 0x72,
	0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x99, 0x01, 0x0a, 0x0d, 0x42, 0x72, 0x65,
	0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x6c, 0x0a, 0x0c, 0x43, 0x61, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x99, 0x01, 0x0a, 0x0d, 0x43, 0x61, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x6e,
	0x0a, 0x0e, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x9b,
	0x01, 0x0a, 0x0f, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2a, 0x0a, 0x0e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x49, 0x6e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x91, 0x01, 0x0a, 0x05, 0x42, 0x72, 0x65,
	0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x91, 0x01, 0x0a,
	0x05, 0x43, 0x61, 0x6b, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x93, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x7f, 0x0a, 0x09, 0x42, 0x72, 0x65, 0x61, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x06, 0x62, 0x72, 0x65, 0x61, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x42, 0x72, 0x65, 0x61,
	0x64, 0x52, 0x06, 0x62, 0x72, 0x65, 0x61, 0x64, 0x73, 0x12, 0x22, 0x0a, 0x05, 0x63, 0x61, 0x6b,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64,
	0x2e, 0x43, 0x61, 0x6b, 0x65, 0x73, 0x52, 0x05, 0x63, 0x61, 0x6b, 0x65, 0x73, 0x12, 0x28, 0x0a,
	0x07, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73, 0x52, 0x07,
	0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73, 0x22, 0x40, 0x0a, 0x11, 0x42, 0x61, 0x6b, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x06,
	0x62, 0x72, 0x65, 0x61, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62,
	0x72, 0x65, 0x61, 0x64, 0x2e, 0x42, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x06, 0x62, 0x72, 0x65, 0x61, 0x64, 0x73, 0x22, 0x42, 0x0a, 0x12, 0x42, 0x61, 0x6b,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x2c, 0x0a, 0x06, 0x62, 0x72, 0x65, 0x61, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x42, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x62, 0x72, 0x65, 0x61, 0x64, 0x73, 0x22, 0x3d, 0x0a,
	0x10, 0x43, 0x61, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x29, 0x0a, 0x05, 0x63, 0x61, 0x6b, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x43, 0x61, 0x6b, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x05, 0x63, 0x61, 0x6b, 0x65, 0x73, 0x22, 0x3f, 0x0a, 0x11,
	0x43, 0x61, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x2a, 0x0a, 0x05, 0x63, 0x61, 0x6b, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x43, 0x61, 0x6b, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x05, 0x63, 0x61, 0x6b, 0x65, 0x73, 0x22, 0x45, 0x0a,
	0x12, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x07, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x43, 0x6f, 0x6f,
	0x6b, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6f,
	0x6b, 0x69, 0x65, 0x73, 0x22, 0x47, 0x0a, 0x13, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x07, 0x63,
	0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62,
	0x72, 0x65, 0x61, 0x64, 0x2e, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x07, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73, 0x32, 0x47, 0x0a,
	0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x72, 0x65, 0x61, 0x64, 0x12, 0x37, 0x0a,
	0x08, 0x47, 0x65, 0x74, 0x42, 0x72, 0x65, 0x61, 0x64, 0x12, 0x13, 0x2e, 0x62, 0x72, 0x65, 0x61,
	0x64, 0x2e, 0x42, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14,
	0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x42, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x4f, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x54, 0x6f, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x3b, 0x0a, 0x09, 0x41, 0x64,
	0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x15, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x49, 0x6e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x1a, 0x15,
	0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x49, 0x6e,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x22, 0x00, 0x32, 0x44, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x42, 0x72,
	0x65, 0x61, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x42, 0x72,
	0x65, 0x61, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e,
	0x42, 0x72, 0x65, 0x61, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x62, 0x72, 0x65, 0x61,
	0x64, 0x2e, 0x42, 0x72, 0x65, 0x61, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x32, 0x57, 0x0a,
	0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x46, 0x72, 0x6f,
	0x6d, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x3e, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x15, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x49, 0x6e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x1a, 0x15, 0x2e,
	0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x49, 0x6e, 0x51,
	0x75, 0x65, 0x75, 0x65, 0x22, 0x00, 0x32, 0x4f, 0x0a, 0x10, 0x53, 0x68, 0x6f, 0x77, 0x57, 0x61,
	0x69, 0x74, 0x69, 0x6e, 0x67, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x3b, 0x0a, 0x09, 0x53, 0x68,
	0x6f, 0x77, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x15, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x49, 0x6e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x1a, 0x15,
	0x2e, 0x62, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x49, 0x6e,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x61, 0x6c, 0x76, 0x61, 0x72, 0x61, 0x64, 0x6f, 0x32,
	0x30, 0x30, 0x34, 0x2f, 0x62, 0x61, 0x6b, 0x65, 0x72, 0x79, 0x2d, 0x67, 0x6f, 0x2f, 0x62, 0x72,
	0x65, 0x61, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_bread_proto_rawDescOnce sync.Once
	file_proto_bread_proto_rawDescData = file_proto_bread_proto_rawDesc
)

func file_proto_bread_proto_rawDescGZIP() []byte {
	file_proto_bread_proto_rawDescOnce.Do(func() {
		file_proto_bread_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_bread_proto_rawDescData)
	})
	return file_proto_bread_proto_rawDescData
}

var file_proto_bread_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_bread_proto_goTypes = []interface{}{
	(*BreadRequest)(nil),        // 0: bread.BreadRequest
	(*BreadResponse)(nil),       // 1: bread.BreadResponse
	(*CakesRequest)(nil),        // 2: bread.CakesRequest
	(*CakesResponse)(nil),       // 3: bread.CakesResponse
	(*CookiesRequest)(nil),      // 4: bread.CookiesRequest
	(*CookiesResponse)(nil),     // 5: bread.CookiesResponse
	(*ClientsInQueue)(nil),      // 6: bread.ClientsInQueue
	(*Bread)(nil),               // 7: bread.Bread
	(*Cakes)(nil),               // 8: bread.Cakes
	(*Cookies)(nil),             // 9: bread.Cookies
	(*BreadList)(nil),           // 10: bread.BreadList
	(*BakeryRequestList)(nil),   // 11: bread.BakeryRequestList
	(*BakeryResponseList)(nil),  // 12: bread.BakeryResponseList
	(*CakesRequestList)(nil),    // 13: bread.CakesRequestList
	(*CakesResponseList)(nil),   // 14: bread.CakesResponseList
	(*CookiesRequestList)(nil),  // 15: bread.CookiesRequestList
	(*CookiesResponseList)(nil), // 16: bread.CookiesResponseList
}
var file_proto_bread_proto_depIdxs = []int32{
	7,  // 0: bread.BreadList.breads:type_name -> bread.Bread
	8,  // 1: bread.BreadList.cakes:type_name -> bread.Cakes
	9,  // 2: bread.BreadList.cookies:type_name -> bread.Cookies
	0,  // 3: bread.BakeryRequestList.breads:type_name -> bread.BreadRequest
	1,  // 4: bread.BakeryResponseList.breads:type_name -> bread.BreadResponse
	2,  // 5: bread.CakesRequestList.cakes:type_name -> bread.CakesRequest
	3,  // 6: bread.CakesResponseList.cakes:type_name -> bread.CakesResponse
	4,  // 7: bread.CookiesRequestList.cookies:type_name -> bread.CookiesRequest
	5,  // 8: bread.CookiesResponseList.cookies:type_name -> bread.CookiesResponse
	0,  // 9: bread.RequestBread.GetBread:input_type -> bread.BreadRequest
	6,  // 10: bread.AddClientToQueue.AddClient:input_type -> bread.ClientsInQueue
	10, // 11: bread.GetBreadList.GetBreadList:input_type -> bread.BreadList
	6,  // 12: bread.DeleteClientFromQueue.DeleteClient:input_type -> bread.ClientsInQueue
	6,  // 13: bread.ShowWaitingQueue.ShowQueue:input_type -> bread.ClientsInQueue
	1,  // 14: bread.RequestBread.GetBread:output_type -> bread.BreadResponse
	6,  // 15: bread.AddClientToQueue.AddClient:output_type -> bread.ClientsInQueue
	10, // 16: bread.GetBreadList.GetBreadList:output_type -> bread.BreadList
	6,  // 17: bread.DeleteClientFromQueue.DeleteClient:output_type -> bread.ClientsInQueue
	6,  // 18: bread.ShowWaitingQueue.ShowQueue:output_type -> bread.ClientsInQueue
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_bread_proto_init() }
func file_proto_bread_proto_init() {
	if File_proto_bread_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_bread_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BreadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BreadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CakesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CakesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CookiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CookiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientsInQueue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bread); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cakes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cookies); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BreadList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BakeryRequestList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BakeryResponseList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CakesRequestList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CakesResponseList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CookiesRequestList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bread_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CookiesResponseList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_bread_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_proto_bread_proto_goTypes,
		DependencyIndexes: file_proto_bread_proto_depIdxs,
		MessageInfos:      file_proto_bread_proto_msgTypes,
	}.Build()
	File_proto_bread_proto = out.File
	file_proto_bread_proto_rawDesc = nil
	file_proto_bread_proto_goTypes = nil
	file_proto_bread_proto_depIdxs = nil
}
