// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/bread.proto

package bread

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bread struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Image         string                 `protobuf:"bytes,10,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bread) Reset() {
	*x = Bread{}
	mi := &file_proto_bread_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bread) ProtoMessage() {}

func (x *Bread) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bread.ProtoReflect.Descriptor instead.
func (*Bread) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{0}
}

func (x *Bread) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bread) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bread) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Bread) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Bread) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Bread) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Bread) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Bread) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Bread) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Bread) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type BuyOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    int32                  `protobuf:"varint,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
	BuyOrderUuid  string                 `protobuf:"bytes,3,opt,name=buyOrderUuid,proto3" json:"buyOrderUuid,omitempty"`
	TotalCost     float32                `protobuf:"fixed32,4,opt,name=totalCost,proto3" json:"totalCost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyOrder) Reset() {
	*x = BuyOrder{}
	mi := &file_proto_bread_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyOrder) ProtoMessage() {}

func (x *BuyOrder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyOrder.ProtoReflect.Descriptor instead.
func (*BuyOrder) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{1}
}

func (x *BuyOrder) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BuyOrder) GetCustomerId() int32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *BuyOrder) GetBuyOrderUuid() string {
	if x != nil {
		return x.BuyOrderUuid
	}
	return ""
}

func (x *BuyOrder) GetTotalCost() float32 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

type BuyOrderDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyOrderId    int32                  `protobuf:"varint,1,opt,name=buyOrderId,proto3" json:"buyOrderId,omitempty"`
	BuyOrderUuid  string                 `protobuf:"bytes,6,opt,name=buyOrderUuid,proto3" json:"buyOrderUuid,omitempty"`
	BreadId       int32                  `protobuf:"varint,2,opt,name=breadId,proto3" json:"breadId,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyOrderDetails) Reset() {
	*x = BuyOrderDetails{}
	mi := &file_proto_bread_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyOrderDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyOrderDetails) ProtoMessage() {}

func (x *BuyOrderDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyOrderDetails.ProtoReflect.Descriptor instead.
func (*BuyOrderDetails) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{2}
}

func (x *BuyOrderDetails) GetBuyOrderId() int32 {
	if x != nil {
		return x.BuyOrderId
	}
	return 0
}

func (x *BuyOrderDetails) GetBuyOrderUuid() string {
	if x != nil {
		return x.BuyOrderUuid
	}
	return ""
}

func (x *BuyOrderDetails) GetBreadId() int32 {
	if x != nil {
		return x.BreadId
	}
	return 0
}

func (x *BuyOrderDetails) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BuyOrderDetails) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BuyOrderDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BuyOrderDetails) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BuyOrderDetails) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type BuyOrderList struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BuyOrders       []*BuyOrder            `protobuf:"bytes,1,rep,name=buyOrders,proto3" json:"buyOrders,omitempty"`
	BuyOrderDetails []*BuyOrderDetails     `protobuf:"bytes,2,rep,name=buyOrderDetails,proto3" json:"buyOrderDetails,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BuyOrderList) Reset() {
	*x = BuyOrderList{}
	mi := &file_proto_bread_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyOrderList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyOrderList) ProtoMessage() {}

func (x *BuyOrderList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyOrderList.ProtoReflect.Descriptor instead.
func (*BuyOrderList) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{3}
}

func (x *BuyOrderList) GetBuyOrders() []*BuyOrder {
	if x != nil {
		return x.BuyOrders
	}
	return nil
}

func (x *BuyOrderList) GetBuyOrderDetails() []*BuyOrderDetails {
	if x != nil {
		return x.BuyOrderDetails
	}
	return nil
}

type BuyOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyOrders     *BuyOrderList          `protobuf:"bytes,3,opt,name=buyOrders,proto3" json:"buyOrders,omitempty"`
	BuyOrderUuid  string                 `protobuf:"bytes,2,opt,name=buy_order_uuid,json=buyOrderUuid,proto3" json:"buy_order_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyOrderRequest) Reset() {
	*x = BuyOrderRequest{}
	mi := &file_proto_bread_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyOrderRequest) ProtoMessage() {}

func (x *BuyOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyOrderRequest.ProtoReflect.Descriptor instead.
func (*BuyOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{4}
}

func (x *BuyOrderRequest) GetBuyOrders() *BuyOrderList {
	if x != nil {
		return x.BuyOrders
	}
	return nil
}

func (x *BuyOrderRequest) GetBuyOrderUuid() string {
	if x != nil {
		return x.BuyOrderUuid
	}
	return ""
}

type BuyOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	BuyOrders     *BuyOrderList          `protobuf:"bytes,3,opt,name=buyOrders,proto3" json:"buyOrders,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyOrderResponse) Reset() {
	*x = BuyOrderResponse{}
	mi := &file_proto_bread_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyOrderResponse) ProtoMessage() {}

func (x *BuyOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyOrderResponse.ProtoReflect.Descriptor instead.
func (*BuyOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{5}
}

func (x *BuyOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BuyOrderResponse) GetBuyOrders() *BuyOrderList {
	if x != nil {
		return x.BuyOrders
	}
	return nil
}

func (x *BuyOrderResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MakeOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BreadMakerId  int32                  `protobuf:"varint,2,opt,name=breadMakerId,proto3" json:"breadMakerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeOrder) Reset() {
	*x = MakeOrder{}
	mi := &file_proto_bread_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeOrder) ProtoMessage() {}

func (x *MakeOrder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeOrder.ProtoReflect.Descriptor instead.
func (*MakeOrder) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{6}
}

func (x *MakeOrder) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MakeOrder) GetBreadMakerId() int32 {
	if x != nil {
		return x.BreadMakerId
	}
	return 0
}

type MakeOrderDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MakeOrderId   int32                  `protobuf:"varint,1,opt,name=makeOrderId,proto3" json:"makeOrderId,omitempty"`
	BreadId       int32                  `protobuf:"varint,2,opt,name=breadId,proto3" json:"breadId,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeOrderDetails) Reset() {
	*x = MakeOrderDetails{}
	mi := &file_proto_bread_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeOrderDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeOrderDetails) ProtoMessage() {}

func (x *MakeOrderDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeOrderDetails.ProtoReflect.Descriptor instead.
func (*MakeOrderDetails) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{7}
}

func (x *MakeOrderDetails) GetMakeOrderId() int32 {
	if x != nil {
		return x.MakeOrderId
	}
	return 0
}

func (x *MakeOrderDetails) GetBreadId() int32 {
	if x != nil {
		return x.BreadId
	}
	return 0
}

func (x *MakeOrderDetails) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *MakeOrderDetails) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MakeOrderDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MakeOrderDetails) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MakeOrderDetails) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type BreadList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Breads        []*Bread               `protobuf:"bytes,1,rep,name=breads,proto3" json:"breads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BreadList) Reset() {
	*x = BreadList{}
	mi := &file_proto_bread_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreadList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreadList) ProtoMessage() {}

func (x *BreadList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreadList.ProtoReflect.Descriptor instead.
func (*BreadList) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{8}
}

func (x *BreadList) GetBreads() []*Bread {
	if x != nil {
		return x.Breads
	}
	return nil
}

type BreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Breads        *BreadList             `protobuf:"bytes,3,opt,name=breads,proto3" json:"breads,omitempty"`
	BuyOrderUuid  string                 `protobuf:"bytes,2,opt,name=buy_order_uuid,json=buyOrderUuid,proto3" json:"buy_order_uuid,omitempty"`
	MakeOrderUuid string                 `protobuf:"bytes,4,opt,name=make_order_uuid,json=makeOrderUuid,proto3" json:"make_order_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BreadRequest) Reset() {
	*x = BreadRequest{}
	mi := &file_proto_bread_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreadRequest) ProtoMessage() {}

func (x *BreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreadRequest.ProtoReflect.Descriptor instead.
func (*BreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{9}
}

func (x *BreadRequest) GetBreads() *BreadList {
	if x != nil {
		return x.Breads
	}
	return nil
}

func (x *BreadRequest) GetBuyOrderUuid() string {
	if x != nil {
		return x.BuyOrderUuid
	}
	return ""
}

func (x *BreadRequest) GetMakeOrderUuid() string {
	if x != nil {
		return x.MakeOrderUuid
	}
	return ""
}

type BreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Breads        *BreadList             `protobuf:"bytes,3,opt,name=breads,proto3" json:"breads,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	BuyOrderId    int32                  `protobuf:"varint,5,opt,name=buy_order_id,json=buyOrderId,proto3" json:"buy_order_id,omitempty"`
	MakeOrderId   int32                  `protobuf:"varint,6,opt,name=make_order_id,json=makeOrderId,proto3" json:"make_order_id,omitempty"`
	BuyOrderUuid  string                 `protobuf:"bytes,7,opt,name=buy_order_uuid,json=buyOrderUuid,proto3" json:"buy_order_uuid,omitempty"`
	MakeOrderUuid string                 `protobuf:"bytes,8,opt,name=make_order_uuid,json=makeOrderUuid,proto3" json:"make_order_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BreadResponse) Reset() {
	*x = BreadResponse{}
	mi := &file_proto_bread_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreadResponse) ProtoMessage() {}

func (x *BreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreadResponse.ProtoReflect.Descriptor instead.
func (*BreadResponse) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{10}
}

func (x *BreadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BreadResponse) GetBreads() *BreadList {
	if x != nil {
		return x.Breads
	}
	return nil
}

func (x *BreadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BreadResponse) GetBuyOrderId() int32 {
	if x != nil {
		return x.BuyOrderId
	}
	return 0
}

func (x *BreadResponse) GetMakeOrderId() int32 {
	if x != nil {
		return x.MakeOrderId
	}
	return 0
}

func (x *BreadResponse) GetBuyOrderUuid() string {
	if x != nil {
		return x.BuyOrderUuid
	}
	return ""
}

func (x *BreadResponse) GetMakeOrderUuid() string {
	if x != nil {
		return x.MakeOrderUuid
	}
	return ""
}

// Admin Service messages
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_bread_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{11}
}

type DashboardStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalOrders      int32                  `protobuf:"varint,1,opt,name=totalOrders,proto3" json:"totalOrders,omitempty"`
	TotalRevenue     float32                `protobuf:"fixed32,2,opt,name=totalRevenue,proto3" json:"totalRevenue,omitempty"`
	TotalProducts    int32                  `protobuf:"varint,3,opt,name=totalProducts,proto3" json:"totalProducts,omitempty"`
	TotalCustomers   int32                  `protobuf:"varint,4,opt,name=totalCustomers,proto3" json:"totalCustomers,omitempty"`
	TotalBreadMakers int32                  `protobuf:"varint,5,opt,name=totalBreadMakers,proto3" json:"totalBreadMakers,omitempty"`
	LowStockCount    int32                  `protobuf:"varint,6,opt,name=lowStockCount,proto3" json:"lowStockCount,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DashboardStats) Reset() {
	*x = DashboardStats{}
	mi := &file_proto_bread_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardStats) ProtoMessage() {}

func (x *DashboardStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardStats.ProtoReflect.Descriptor instead.
func (*DashboardStats) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{12}
}

func (x *DashboardStats) GetTotalOrders() int32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *DashboardStats) GetTotalRevenue() float32 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *DashboardStats) GetTotalProducts() int32 {
	if x != nil {
		return x.TotalProducts
	}
	return 0
}

func (x *DashboardStats) GetTotalCustomers() int32 {
	if x != nil {
		return x.TotalCustomers
	}
	return 0
}

func (x *DashboardStats) GetTotalBreadMakers() int32 {
	if x != nil {
		return x.TotalBreadMakers
	}
	return 0
}

func (x *DashboardStats) GetLowStockCount() int32 {
	if x != nil {
		return x.LowStockCount
	}
	return 0
}

type Customer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_proto_bread_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{13}
}

func (x *Customer) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Customer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Customer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Customer) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Customer) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CustomerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customers     []*Customer            `protobuf:"bytes,1,rep,name=customers,proto3" json:"customers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerList) Reset() {
	*x = CustomerList{}
	mi := &file_proto_bread_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerList) ProtoMessage() {}

func (x *CustomerList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerList.ProtoReflect.Descriptor instead.
func (*CustomerList) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{14}
}

func (x *CustomerList) GetCustomers() []*Customer {
	if x != nil {
		return x.Customers
	}
	return nil
}

type BreadMakerProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BreadMakerProto) Reset() {
	*x = BreadMakerProto{}
	mi := &file_proto_bread_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreadMakerProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreadMakerProto) ProtoMessage() {}

func (x *BreadMakerProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreadMakerProto.ProtoReflect.Descriptor instead.
func (*BreadMakerProto) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{15}
}

func (x *BreadMakerProto) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BreadMakerProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BreadMakerProto) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BreadMakerProto) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BreadMakerProto) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type BreadMakerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BreadMakers   []*BreadMakerProto     `protobuf:"bytes,1,rep,name=breadMakers,proto3" json:"breadMakers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BreadMakerList) Reset() {
	*x = BreadMakerList{}
	mi := &file_proto_bread_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreadMakerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreadMakerList) ProtoMessage() {}

func (x *BreadMakerList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreadMakerList.ProtoReflect.Descriptor instead.
func (*BreadMakerList) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{16}
}

func (x *BreadMakerList) GetBreadMakers() []*BreadMakerProto {
	if x != nil {
		return x.BreadMakers
	}
	return nil
}

type CreateBreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBreadRequest) Reset() {
	*x = CreateBreadRequest{}
	mi := &file_proto_bread_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBreadRequest) ProtoMessage() {}

func (x *CreateBreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBreadRequest.ProtoReflect.Descriptor instead.
func (*CreateBreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{17}
}

func (x *CreateBreadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBreadRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateBreadRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateBreadRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBreadRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateBreadRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type UpdateBreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Image         string                 `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBreadRequest) Reset() {
	*x = UpdateBreadRequest{}
	mi := &file_proto_bread_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBreadRequest) ProtoMessage() {}

func (x *UpdateBreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBreadRequest.ProtoReflect.Descriptor instead.
func (*UpdateBreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateBreadRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBreadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateBreadRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateBreadRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateBreadRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateBreadRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateBreadRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type DeleteBreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBreadRequest) Reset() {
	*x = DeleteBreadRequest{}
	mi := &file_proto_bread_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBreadRequest) ProtoMessage() {}

func (x *DeleteBreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBreadRequest.ProtoReflect.Descriptor instead.
func (*DeleteBreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteBreadRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyOrderUuid  string                 `protobuf:"bytes,1,opt,name=buyOrderUuid,proto3" json:"buyOrderUuid,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_proto_bread_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateOrderStatusRequest) GetBuyOrderUuid() string {
	if x != nil {
		return x.BuyOrderUuid
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type BreadIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BreadIdRequest) Reset() {
	*x = BreadIdRequest{}
	mi := &file_proto_bread_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreadIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreadIdRequest) ProtoMessage() {}

func (x *BreadIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreadIdRequest.ProtoReflect.Descriptor instead.
func (*BreadIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{21}
}

func (x *BreadIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CustomerIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerIdRequest) Reset() {
	*x = CustomerIdRequest{}
	mi := &file_proto_bread_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerIdRequest) ProtoMessage() {}

func (x *CustomerIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerIdRequest.ProtoReflect.Descriptor instead.
func (*CustomerIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{22}
}

func (x *CustomerIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BreadMakerIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BreadMakerIdRequest) Reset() {
	*x = BreadMakerIdRequest{}
	mi := &file_proto_bread_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreadMakerIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreadMakerIdRequest) ProtoMessage() {}

func (x *BreadMakerIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreadMakerIdRequest.ProtoReflect.Descriptor instead.
func (*BreadMakerIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{23}
}

func (x *BreadMakerIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CustomerOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	Orders        []*BuyOrder            `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerOrdersResponse) Reset() {
	*x = CustomerOrdersResponse{}
	mi := &file_proto_bread_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerOrdersResponse) ProtoMessage() {}

func (x *CustomerOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerOrdersResponse.ProtoReflect.Descriptor instead.
func (*CustomerOrdersResponse) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{24}
}

func (x *CustomerOrdersResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *CustomerOrdersResponse) GetOrders() []*BuyOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

type MakerOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Maker         *BreadMakerProto       `protobuf:"bytes,1,opt,name=maker,proto3" json:"maker,omitempty"`
	Orders        []*MakeOrderProto      `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakerOrdersResponse) Reset() {
	*x = MakerOrdersResponse{}
	mi := &file_proto_bread_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakerOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakerOrdersResponse) ProtoMessage() {}

func (x *MakerOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakerOrdersResponse.ProtoReflect.Descriptor instead.
func (*MakerOrdersResponse) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{25}
}

func (x *MakerOrdersResponse) GetMaker() *BreadMakerProto {
	if x != nil {
		return x.Maker
	}
	return nil
}

func (x *MakerOrdersResponse) GetOrders() []*MakeOrderProto {
	if x != nil {
		return x.Orders
	}
	return nil
}

type MakeOrderProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BreadMakerId  int32                  `protobuf:"varint,2,opt,name=breadMakerId,proto3" json:"breadMakerId,omitempty"`
	MakeOrderUuid string                 `protobuf:"bytes,3,opt,name=makeOrderUuid,proto3" json:"makeOrderUuid,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Breads        []*Bread               `protobuf:"bytes,6,rep,name=breads,proto3" json:"breads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeOrderProto) Reset() {
	*x = MakeOrderProto{}
	mi := &file_proto_bread_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeOrderProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeOrderProto) ProtoMessage() {}

func (x *MakeOrderProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeOrderProto.ProtoReflect.Descriptor instead.
func (*MakeOrderProto) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{26}
}

func (x *MakeOrderProto) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MakeOrderProto) GetBreadMakerId() int32 {
	if x != nil {
		return x.BreadMakerId
	}
	return 0
}

func (x *MakeOrderProto) GetMakeOrderUuid() string {
	if x != nil {
		return x.MakeOrderUuid
	}
	return ""
}

func (x *MakeOrderProto) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MakeOrderProto) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *MakeOrderProto) GetBreads() []*Bread {
	if x != nil {
		return x.Breads
	}
	return nil
}

type MakeOrderList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MakeOrders    []*MakeOrderProto      `protobuf:"bytes,1,rep,name=makeOrders,proto3" json:"makeOrders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeOrderList) Reset() {
	*x = MakeOrderList{}
	mi := &file_proto_bread_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeOrderList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeOrderList) ProtoMessage() {}

func (x *MakeOrderList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bread_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeOrderList.ProtoReflect.Descriptor instead.
func (*MakeOrderList) Descriptor() ([]byte, []int) {
	return file_proto_bread_proto_rawDescGZIP(), []int{27}
}

func (x *MakeOrderList) GetMakeOrders() []*MakeOrderProto {
	if x != nil {
		return x.MakeOrders
	}
	return nil
}

var File_proto_bread_proto protoreflect.FileDescriptor

const file_proto_bread_proto_rawDesc = "" +
	"\n" +
	"\x11proto/bread.proto\x12\x05bread\"\xfd\x01\n" +
	"\x05Bread\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1c\n" +
	"\tcreatedAt\x18\b \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\t \x01(\tR\tupdatedAt\x12\x14\n" +
	"\x05image\x18\n" +
	" \x01(\tR\x05image\"|\n" +
	"\bBuyOrder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1e\n" +
	"\n" +
	"customerId\x18\x02 \x01(\x05R\n" +
	"customerId\x12\"\n" +
	"\fbuyOrderUuid\x18\x03 \x01(\tR\fbuyOrderUuid\x12\x1c\n" +
	"\ttotalCost\x18\x04 \x01(\x02R\ttotalCost\"\xf7\x01\n" +
	"\x0fBuyOrderDetails\x12\x1e\n" +
	"\n" +
	"buyOrderId\x18\x01 \x01(\x05R\n" +
	"buyOrderId\x12\"\n" +
	"\fbuyOrderUuid\x18\x06 \x01(\tR\fbuyOrderUuid\x12\x18\n" +
	"\abreadId\x18\x02 \x01(\x05R\abreadId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\x7f\n" +
	"\fBuyOrderList\x12-\n" +
	"\tbuyOrders\x18\x01 \x03(\v2\x0f.bread.BuyOrderR\tbuyOrders\x12@\n" +
	"\x0fbuyOrderDetails\x18\x02 \x03(\v2\x16.bread.BuyOrderDetailsR\x0fbuyOrderDetails\"j\n" +
	"\x0fBuyOrderRequest\x121\n" +
	"\tbuyOrders\x18\x03 \x01(\v2\x13.bread.BuyOrderListR\tbuyOrders\x12$\n" +
	"\x0ebuy_order_uuid\x18\x02 \x01(\tR\fbuyOrderUuid\"u\n" +
	"\x10BuyOrderResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x121\n" +
	"\tbuyOrders\x18\x03 \x01(\v2\x13.bread.BuyOrderListR\tbuyOrders\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"?\n" +
	"\tMakeOrder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\"\n" +
	"\fbreadMakerId\x18\x02 \x01(\x05R\fbreadMakerId\"\xd6\x01\n" +
	"\x10MakeOrderDetails\x12 \n" +
	"\vmakeOrderId\x18\x01 \x01(\x05R\vmakeOrderId\x12\x18\n" +
	"\abreadId\x18\x02 \x01(\x05R\abreadId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"1\n" +
	"\tBreadList\x12$\n" +
	"\x06breads\x18\x01 \x03(\v2\f.bread.BreadR\x06breads\"\x86\x01\n" +
	"\fBreadRequest\x12(\n" +
	"\x06breads\x18\x03 \x01(\v2\x10.bread.BreadListR\x06breads\x12$\n" +
	"\x0ebuy_order_uuid\x18\x02 \x01(\tR\fbuyOrderUuid\x12&\n" +
	"\x0fmake_order_uuid\x18\x04 \x01(\tR\rmakeOrderUuid\"\xfd\x01\n" +
	"\rBreadResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12(\n" +
	"\x06breads\x18\x03 \x01(\v2\x10.bread.BreadListR\x06breads\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12 \n" +
	"\fbuy_order_id\x18\x05 \x01(\x05R\n" +
	"buyOrderId\x12\"\n" +
	"\rmake_order_id\x18\x06 \x01(\x05R\vmakeOrderId\x12$\n" +
	"\x0ebuy_order_uuid\x18\a \x01(\tR\fbuyOrderUuid\x12&\n" +
	"\x0fmake_order_uuid\x18\b \x01(\tR\rmakeOrderUuid\"\a\n" +
	"\x05Empty\"\xf6\x01\n" +
	"\x0eDashboardStats\x12 \n" +
	"\vtotalOrders\x18\x01 \x01(\x05R\vtotalOrders\x12\"\n" +
	"\ftotalRevenue\x18\x02 \x01(\x02R\ftotalRevenue\x12$\n" +
	"\rtotalProducts\x18\x03 \x01(\x05R\rtotalProducts\x12&\n" +
	"\x0etotalCustomers\x18\x04 \x01(\x05R\x0etotalCustomers\x12*\n" +
	"\x10totalBreadMakers\x18\x05 \x01(\x05R\x10totalBreadMakers\x12$\n" +
	"\rlowStockCount\x18\x06 \x01(\x05R\rlowStockCount\"\x80\x01\n" +
	"\bCustomer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x05 \x01(\tR\tupdatedAt\"=\n" +
	"\fCustomerList\x12-\n" +
	"\tcustomers\x18\x01 \x03(\v2\x0f.bread.CustomerR\tcustomers\"\x87\x01\n" +
	"\x0fBreadMakerProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x05 \x01(\tR\tupdatedAt\"J\n" +
	"\x0eBreadMakerList\x128\n" +
	"\vbreadMakers\x18\x01 \x03(\v2\x16.bread.BreadMakerProtoR\vbreadMakers\"\xa6\x01\n" +
	"\x12CreateBreadRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\"\xb6\x01\n" +
	"\x12UpdateBreadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x14\n" +
	"\x05image\x18\a \x01(\tR\x05image\"$\n" +
	"\x12DeleteBreadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"V\n" +
	"\x18UpdateOrderStatusRequest\x12\"\n" +
	"\fbuyOrderUuid\x18\x01 \x01(\tR\fbuyOrderUuid\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\" \n" +
	"\x0eBreadIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"#\n" +
	"\x11CustomerIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"%\n" +
	"\x13BreadMakerIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"n\n" +
	"\x16CustomerOrdersResponse\x12+\n" +
	"\bcustomer\x18\x01 \x01(\v2\x0f.bread.CustomerR\bcustomer\x12'\n" +
	"\x06orders\x18\x02 \x03(\v2\x0f.bread.BuyOrderR\x06orders\"r\n" +
	"\x13MakerOrdersResponse\x12,\n" +
	"\x05maker\x18\x01 \x01(\v2\x16.bread.BreadMakerProtoR\x05maker\x12-\n" +
	"\x06orders\x18\x02 \x03(\v2\x15.bread.MakeOrderProtoR\x06orders\"\xcc\x01\n" +
	"\x0eMakeOrderProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\"\n" +
	"\fbreadMakerId\x18\x02 \x01(\x05R\fbreadMakerId\x12$\n" +
	"\rmakeOrderUuid\x18\x03 \x01(\tR\rmakeOrderUuid\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x05 \x01(\tR\tupdatedAt\x12$\n" +
	"\x06breads\x18\x06 \x03(\v2\f.bread.BreadR\x06breads\"F\n" +
	"\rMakeOrderList\x125\n" +
	"\n" +
	"makeOrders\x18\x01 \x03(\v2\x15.bread.MakeOrderProtoR\n" +
	"makeOrders2\xc9\x01\n" +
	"\tMakeBread\x128\n" +
	"\tBakeBread\x12\x13.bread.BreadRequest\x1a\x14.bread.BreadResponse\"\x00\x12@\n" +
	"\x11SendBreadToBakery\x12\x13.bread.BreadRequest\x1a\x14.bread.BreadResponse\"\x00\x12@\n" +
	"\x0fMadeBreadStream\x12\x13.bread.BreadRequest\x1a\x14.bread.BreadResponse\"\x000\x012\xa0\x01\n" +
	"\x0eCheckInventory\x12B\n" +
	"\x13CheckBreadInventory\x12\x13.bread.BreadRequest\x1a\x14.bread.BreadResponse\"\x00\x12J\n" +
	"\x19CheckBreadInventoryStream\x12\x13.bread.BreadRequest\x1a\x14.bread.BreadResponse\"\x000\x012\x84\x01\n" +
	"\bBuyBread\x127\n" +
	"\bBuyBread\x12\x13.bread.BreadRequest\x1a\x14.bread.BreadResponse\"\x00\x12?\n" +
	"\x0eBuyBreadStream\x12\x13.bread.BreadRequest\x1a\x14.bread.BreadResponse\"\x000\x012\x97\x01\n" +
	"\x0fBuyOrderService\x12=\n" +
	"\bBuyOrder\x12\x16.bread.BuyOrderRequest\x1a\x17.bread.BuyOrderResponse\"\x00\x12E\n" +
	"\x0eBuyOrderStream\x12\x16.bread.BuyOrderRequest\x1a\x17.bread.BuyOrderResponse\"\x000\x012\x90\x01\n" +
	"\x0eRemoveOldBread\x12:\n" +
	"\vRemoveBread\x12\x13.bread.BreadRequest\x1a\x14.bread.BreadResponse\"\x00\x12B\n" +
	"\x11RemoveBreadStream\x12\x13.bread.BreadRequest\x1a\x14.bread.BreadResponse\"\x000\x012\x8e\x01\n" +
	"\x10MakeOrderService\x128\n" +
	"\tMakeOrder\x12\x13.bread.BreadRequest\x1a\x14.bread.BreadResponse\"\x00\x12@\n" +
	"\x0fMakeOrderStream\x12\x13.bread.BreadRequest\x1a\x14.bread.BreadResponse\"\x000\x012\xc3\x06\n" +
	"\fAdminService\x128\n" +
	"\x11GetDashboardStats\x12\f.bread.Empty\x1a\x15.bread.DashboardStats\x124\n" +
	"\x0fGetAllCustomers\x12\f.bread.Empty\x1a\x13.bread.CustomerList\x128\n" +
	"\x11GetAllBreadMakers\x12\f.bread.Empty\x1a\x15.bread.BreadMakerList\x12-\n" +
	"\vGetAllBread\x12\f.bread.Empty\x1a\x10.bread.BreadList\x123\n" +
	"\fGetBreadById\x12\x15.bread.BreadIdRequest\x1a\f.bread.Bread\x126\n" +
	"\vCreateBread\x12\x19.bread.CreateBreadRequest\x1a\f.bread.Bread\x126\n" +
	"\vUpdateBread\x12\x19.bread.UpdateBreadRequest\x1a\f.bread.Bread\x126\n" +
	"\vDeleteBread\x12\x19.bread.DeleteBreadRequest\x1a\f.bread.Empty\x123\n" +
	"\x11GetLowStockAlerts\x12\f.bread.Empty\x1a\x10.bread.BreadList\x12E\n" +
	"\x11UpdateOrderStatus\x12\x1f.bread.UpdateOrderStatusRequest\x1a\x0f.bread.BuyOrder\x12L\n" +
	"\x11GetCustomerOrders\x12\x18.bread.CustomerIdRequest\x1a\x1d.bread.CustomerOrdersResponse\x12H\n" +
	"\x0eGetMakerOrders\x12\x1a.bread.BreadMakerIdRequest\x1a\x1a.bread.MakerOrdersResponse\x121\n" +
	"\fGetAllOrders\x12\f.bread.Empty\x1a\x13.bread.BuyOrderList\x126\n" +
	"\x10GetAllMakeOrders\x12\f.bread.Empty\x1a\x14.bread.MakeOrderListB*Z(github.com/calvarado2004/bakery-go/breadb\x06proto3"

var (
	file_proto_bread_proto_rawDescOnce sync.Once
	file_proto_bread_proto_rawDescData []byte
)

func file_proto_bread_proto_rawDescGZIP() []byte {
	file_proto_bread_proto_rawDescOnce.Do(func() {
		file_proto_bread_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bread_proto_rawDesc), len(file_proto_bread_proto_rawDesc)))
	})
	return file_proto_bread_proto_rawDescData
}

var file_proto_bread_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_bread_proto_goTypes = []any{
	(*Bread)(nil),                    // 0: bread.Bread
	(*BuyOrder)(nil),                 // 1: bread.BuyOrder
	(*BuyOrderDetails)(nil),          // 2: bread.BuyOrderDetails
	(*BuyOrderList)(nil),             // 3: bread.BuyOrderList
	(*BuyOrderRequest)(nil),          // 4: bread.BuyOrderRequest
	(*BuyOrderResponse)(nil),         // 5: bread.BuyOrderResponse
	(*MakeOrder)(nil),                // 6: bread.MakeOrder
	(*MakeOrderDetails)(nil),         // 7: bread.MakeOrderDetails
	(*BreadList)(nil),                // 8: bread.BreadList
	(*BreadRequest)(nil),             // 9: bread.BreadRequest
	(*BreadResponse)(nil),            // 10: bread.BreadResponse
	(*Empty)(nil),                    // 11: bread.Empty
	(*DashboardStats)(nil),           // 12: bread.DashboardStats
	(*Customer)(nil),                 // 13: bread.Customer
	(*CustomerList)(nil),             // 14: bread.CustomerList
	(*BreadMakerProto)(nil),          // 15: bread.BreadMakerProto
	(*BreadMakerList)(nil),           // 16: bread.BreadMakerList
	(*CreateBreadRequest)(nil),       // 17: bread.CreateBreadRequest
	(*UpdateBreadRequest)(nil),       // 18: bread.UpdateBreadRequest
	(*DeleteBreadRequest)(nil),       // 19: bread.DeleteBreadRequest
	(*UpdateOrderStatusRequest)(nil), // 20: bread.UpdateOrderStatusRequest
	(*BreadIdRequest)(nil),           // 21: bread.BreadIdRequest
	(*CustomerIdRequest)(nil),        // 22: bread.CustomerIdRequest
	(*BreadMakerIdRequest)(nil),      // 23: bread.BreadMakerIdRequest
	(*CustomerOrdersResponse)(nil),   // 24: bread.CustomerOrdersResponse
	(*MakerOrdersResponse)(nil),      // 25: bread.MakerOrdersResponse
	(*MakeOrderProto)(nil),           // 26: bread.MakeOrderProto
	(*MakeOrderList)(nil),            // 27: bread.MakeOrderList
}
var file_proto_bread_proto_depIdxs = []int32{
	1,  // 0: bread.BuyOrderList.buyOrders:type_name -> bread.BuyOrder
	2,  // 1: bread.BuyOrderList.buyOrderDetails:type_name -> bread.BuyOrderDetails
	3,  // 2: bread.BuyOrderRequest.buyOrders:type_name -> bread.BuyOrderList
	3,  // 3: bread.BuyOrderResponse.buyOrders:type_name -> bread.BuyOrderList
	0,  // 4: bread.BreadList.breads:type_name -> bread.Bread
	8,  // 5: bread.BreadRequest.breads:type_name -> bread.BreadList
	8,  // 6: bread.BreadResponse.breads:type_name -> bread.BreadList
	13, // 7: bread.CustomerList.customers:type_name -> bread.Customer
	15, // 8: bread.BreadMakerList.breadMakers:type_name -> bread.BreadMakerProto
	13, // 9: bread.CustomerOrdersResponse.customer:type_name -> bread.Customer
	1,  // 10: bread.CustomerOrdersResponse.orders:type_name -> bread.BuyOrder
	15, // 11: bread.MakerOrdersResponse.maker:type_name -> bread.BreadMakerProto
	26, // 12: bread.MakerOrdersResponse.orders:type_name -> bread.MakeOrderProto
	0,  // 13: bread.MakeOrderProto.breads:type_name -> bread.Bread
	26, // 14: bread.MakeOrderList.makeOrders:type_name -> bread.MakeOrderProto
	9,  // 15: bread.MakeBread.BakeBread:input_type -> bread.BreadRequest
	9,  // 16: bread.MakeBread.SendBreadToBakery:input_type -> bread.BreadRequest
	9,  // 17: bread.MakeBread.MadeBreadStream:input_type -> bread.BreadRequest
	9,  // 18: bread.CheckInventory.CheckBreadInventory:input_type -> bread.BreadRequest
	9,  // 19: bread.CheckInventory.CheckBreadInventoryStream:input_type -> bread.BreadRequest
	9,  // 20: bread.BuyBread.BuyBread:input_type -> bread.BreadRequest
	9,  // 21: bread.BuyBread.BuyBreadStream:input_type -> bread.BreadRequest
	4,  // 22: bread.BuyOrderService.BuyOrder:input_type -> bread.BuyOrderRequest
	4,  // 23: bread.BuyOrderService.BuyOrderStream:input_type -> bread.BuyOrderRequest
	9,  // 24: bread.RemoveOldBread.RemoveBread:input_type -> bread.BreadRequest
	9,  // 25: bread.RemoveOldBread.RemoveBreadStream:input_type -> bread.BreadRequest
	9,  // 26: bread.MakeOrderService.MakeOrder:input_type -> bread.BreadRequest
	9,  // 27: bread.MakeOrderService.MakeOrderStream:input_type -> bread.BreadRequest
	11, // 28: bread.AdminService.GetDashboardStats:input_type -> bread.Empty
	11, // 29: bread.AdminService.GetAllCustomers:input_type -> bread.Empty
	11, // 30: bread.AdminService.GetAllBreadMakers:input_type -> bread.Empty
	11, // 31: bread.AdminService.GetAllBread:input_type -> bread.Empty
	21, // 32: bread.AdminService.GetBreadById:input_type -> bread.BreadIdRequest
	17, // 33: bread.AdminService.CreateBread:input_type -> bread.CreateBreadRequest
	18, // 34: bread.AdminService.UpdateBread:input_type -> bread.UpdateBreadRequest
	19, // 35: bread.AdminService.DeleteBread:input_type -> bread.DeleteBreadRequest
	11, // 36: bread.AdminService.GetLowStockAlerts:input_type -> bread.Empty
	20, // 37: bread.AdminService.UpdateOrderStatus:input_type -> bread.UpdateOrderStatusRequest
	22, // 38: bread.AdminService.GetCustomerOrders:input_type -> bread.CustomerIdRequest
	23, // 39: bread.AdminService.GetMakerOrders:input_type -> bread.BreadMakerIdRequest
	11, // 40: bread.AdminService.GetAllOrders:input_type -> bread.Empty
	11, // 41: bread.AdminService.GetAllMakeOrders:input_type -> bread.Empty
	10, // 42: bread.MakeBread.BakeBread:output_type -> bread.BreadResponse
	10, // 43: bread.MakeBread.SendBreadToBakery:output_type -> bread.BreadResponse
	10, // 44: bread.MakeBread.MadeBreadStream:output_type -> bread.BreadResponse
	10, // 45: bread.CheckInventory.CheckBreadInventory:output_type -> bread.BreadResponse
	10, // 46: bread.CheckInventory.CheckBreadInventoryStream:output_type -> bread.BreadResponse
	10, // 47: bread.BuyBread.BuyBread:output_type -> bread.BreadResponse
	10, // 48: bread.BuyBread.BuyBreadStream:output_type -> bread.BreadResponse
	5,  // 49: bread.BuyOrderService.BuyOrder:output_type -> bread.BuyOrderResponse
	5,  // 50: bread.BuyOrderService.BuyOrderStream:output_type -> bread.BuyOrderResponse
	10, // 51: bread.RemoveOldBread.RemoveBread:output_type -> bread.BreadResponse
	10, // 52: bread.RemoveOldBread.RemoveBreadStream:output_type -> bread.BreadResponse
	10, // 53: bread.MakeOrderService.MakeOrder:output_type -> bread.BreadResponse
	10, // 54: bread.MakeOrderService.MakeOrderStream:output_type -> bread.BreadResponse
	12, // 55: bread.AdminService.GetDashboardStats:output_type -> bread.DashboardStats
	14, // 56: bread.AdminService.GetAllCustomers:output_type -> bread.CustomerList
	16, // 57: bread.AdminService.GetAllBreadMakers:output_type -> bread.BreadMakerList
	8,  // 58: bread.AdminService.GetAllBread:output_type -> bread.BreadList
	0,  // 59: bread.AdminService.GetBreadById:output_type -> bread.Bread
	0,  // 60: bread.AdminService.CreateBread:output_type -> bread.Bread
	0,  // 61: bread.AdminService.UpdateBread:output_type -> bread.Bread
	11, // 62: bread.AdminService.DeleteBread:output_type -> bread.Empty
	8,  // 63: bread.AdminService.GetLowStockAlerts:output_type -> bread.BreadList
	1,  // 64: bread.AdminService.UpdateOrderStatus:output_type -> bread.BuyOrder
	24, // 65: bread.AdminService.GetCustomerOrders:output_type -> bread.CustomerOrdersResponse
	25, // 66: bread.AdminService.GetMakerOrders:output_type -> bread.MakerOrdersResponse
	3,  // 67: bread.AdminService.GetAllOrders:output_type -> bread.BuyOrderList
	27, // 68: bread.AdminService.GetAllMakeOrders:output_type -> bread.MakeOrderList
	42, // [42:69] is the sub-list for method output_type
	15, // [15:42] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_bread_proto_init() }
func file_proto_bread_proto_init() {
	if File_proto_bread_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bread_proto_rawDesc), len(file_proto_bread_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   7,
		},
		GoTypes:           file_proto_bread_proto_goTypes,
		DependencyIndexes: file_proto_bread_proto_depIdxs,
		MessageInfos:      file_proto_bread_proto_msgTypes,
	}.Build()
	File_proto_bread_proto = out.File
	file_proto_bread_proto_goTypes = nil
	file_proto_bread_proto_depIdxs = nil
}
