apiVersion: apps/v1
kind: Deployment
metadata:
  name: bakery-buyers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bakery-buyers
  template:
    metadata:
      labels:
        app: bakery-buyers
    spec:
      containers:
        - name: bakery-buyers
          image: docker.io/calvarado2004/bakery-go-buyers
          env:
            - name: BAKERY_SERVICE_ADDR
              value: "bakery-server-service:50051"
            - name: ACTIVEMQ_SERVICE_ADDR
              value: "amqp://guest:guest@rabbitmq-service:5672/"