apiVersion: apps/v1
kind: Deployment
metadata:
  name: bakery-makers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bakery-makers
  template:
    metadata:
      labels:
        app: bakery-makers
    spec:
      containers:
        - name: bakery-makers
          image: docker.io/calvarado2004/bakery-go-makers
          env:
            - name: BAKERY_SERVICE_ADDR
              value: "bakery-server-service:50051"
            - name: RABBITMQ_SERVICE_ADDR
              value: "amqp://guest:guest@rabbitmq-service:5672/"
            - name: DSN
              value: "host=postgres-service port=5432 user=postgres password=postgres dbname=bakery sslmode=disable timezone=UTC connect_timeout=5"