apiVersion: apps/v1
kind: Deployment
metadata:
  name: bakery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bakery-server
  template:
    metadata:
      labels:
        app: bakery-server
    spec:
      containers:
        - name: bakery-server
          image: docker.io/calvarado2004/bakery-go-server
          ports:
            - containerPort: 50051
          env:
            - name: BAKERY_SERVICE_ADDR
              value: "0.0.0.0:50051"
            - name: ACTIVEMQ_SERVICE_ADDR
              value: "amqp://guest:guest@rabbitmq-service:5672/"
            - name: DSN
              value: "host=postgres-service port=5432 user=postgres password=postgres dbname=bakery sslmode=disable timezone=UTC connect_timeout=5"
---
apiVersion: v1
kind: Service
metadata:
  name: bakery-server-service
  labels:
    app: bakery-server
spec:
  ports:
    - port: 50051
      protocol: TCP
      name: grpc
  selector:
    app: bakery-server